### ISSUE TITLE
[bug]: dark mode classes are not being generated or applied

### ISSUE THREAD

**Issue by mtzrmzia** [BayBreezy/ui-thing#79]
### Describe the bug
After setting up a fresh installation using pnpm and activating dark mode, the dark mode classes are not being generated or applied in the browser. The dark class is present on the root <html> element, but the corresponding styles are missing in the compiled CSS.

### Expected Behavior
The dark mode classes should be generated by TailwindCSS and applied to the DOM when the dark class is present on the root element.

### Actual Behavior

- The dark class is present on the root <html> element (see screenshot).
- However, the dark mode styles are not being generated in the final CSS.
- No visual changes occur when switching to dark mode.

![Image](https://github.com/user-attachments/assets/c1505069-3882-4dae-b0a5-dc1569a1b161)

**Comment by BayBreezy** [comment]
Hey, can youshare your css file an dthe TW config file plz?

**Comment by mtzrmzia** [comment]
Hey @BayBreezy there you go

`tailwind.css`
```css
@tailwind base;
@tailwind components;
@tailwind utilities;


@layer base {
    :root {
        --background: 0 0% 100%;
        --foreground: 0 0% 3.9%;
        --card: 0 0% 100%;
        --card-foreground: 0 0% 3.9%;
        --popover: 0 0% 100%;
        --popover-foreground: 0 0% 3.9%;
        --primary: 0 0% 9%;
        --primary-foreground: 0 0% 98%;
        --secondary: 0 0% 96.1%;
        --secondary-foreground: 0 0% 9%;
        --muted: 0 0% 96.1%;
        --muted-foreground: 0 0% 45.1%;
        --accent: 0 0% 96.1%;
        --accent-foreground: 0 0% 9%;
        --destructive: 0 84.2% 60.2%;
        --destructive-foreground: 0 0% 98%;
        --border: 0 0% 89.8%;
        --input: 0 0% 89.8%;
        --ring: 0 0% 3.9%;
        --radius: 0.5rem;
        --sidebar-background: 0 0% 98%;
        --sidebar-foreground: 0 0% 3.9%;
        --sidebar-primary: 0 0% 9%;
        --sidebar-primary-foreground: 0 0% 98%;
        --sidebar-accent: 0 0% 96.1%;
        --sidebar-accent-foreground: 0 0% 9%;
        --sidebar-border: 0 0% 89.8%;
        --sidebar-ring: 0 0% 9%;
        --sidebar-input: 0 0% 89.8%;
    }

    .dark {
        --background: 0 0% 3.9%;
        --foreground: 0 0% 98%;
        --card: 0 0% 3.9%;
        --card-foreground: 0 0% 98%;
        --popover: 0 0% 3.9%;
        --popover-foreground: 0 0% 98%;
        --primary: 0 0% 98%;
        --primary-foreground: 0 0% 9%;
        --secondary: 0 0% 14.9%;
        --secondary-foreground: 0 0% 98%;
        --muted: 0 0% 14.9%;
        --muted-foreground: 0 0% 63.9%;
        --accent: 0 0% 14.9%;
        --accent-foreground: 0 0% 98%;
        --destructive: 0 62.8% 30.6%;
        --destructive-foreground: 0 0% 98%;
        --border: 0 0% 14.9%;
        --input: 0 0% 14.9%;
        --ring: 0 0% 83.1%;
        --sidebar-background: 0 0% 9%;
        --sidebar-foreground: 0 0% 98%;
        --sidebar-primary: 346.8 77.2% 49.8%;
        --sidebar-primary-foreground: 0 0% 98%;
        --sidebar-accent: 0 0% 14.9%;
        --sidebar-accent-foreground: 0 0% 98%;
        --sidebar-border: 0 0% 14.9%;
        --sidebar-ring: 346.8 77.2% 49.8%;
        --sidebar-input: 0 0% 14.9%;
    }
}

@layer base {
    * {
        @apply border-border;
    }

    html {
        @apply antialiased;
    }

    body {
        @apply bg-background text-foreground;
        font-feature-settings: "cv02", "cv03", "cv04", "cv11";
    }
}
```

`tailwind.config.js`
```js
const { fontFamily } = require("tailwindcss/defaultTheme");

/**@type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      container: {
        center: true,
        padding: {
          DEFAULT: "1rem",
          sm: "2rem",
          lg: "4rem",
        },
        screens: {
          "2xl": "1300px",
        },
      },
      fontFamily: {
        sans: [
          `Inter, ${fontFamily.sans.join(", ")}`,
          {
            fontFeatureSettings: '"cv02","cv03","cv04","cv11"',
          },
        ],
        mono: ["'Fira Code'", ...fontFamily.mono],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        shine: {
          from: { backgroundPosition: "200% 0" },
          to: { backgroundPosition: "-200% 0" },
        },
        meteor: {
          "0%": { transform: "rotate(215deg) translateX(0)", opacity: 1 },
          "70%": { opacity: 1 },
          "100%": {
            transform: "rotate(215deg) translateX(-500px)",
            opacity: 0,
          },
        },
        grid: {
          "0%": { transform: "translateY(-50%)" },
          "100%": { transform: "translateY(0)" },
        },
        "border-beam": {
          "100%": {
            "offset-distance": "100%",
          },
        },
        "accordion-down": {
          from: { height: "0px" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0px" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        fadeOut: {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        "collapse-down": {
          from: { height: "0px" },
          to: { height: "var(--radix-collapsible-content-height)" },
        },
        "collapse-up": {
          from: { height: "var(--radix-collapsible-content-height)" },
          to: { height: "0px" },
        },
      },
      animation: {
        shine: "shine 8s ease-in-out infinite",
        meteor: "meteor 5s linear infinite",
        grid: "grid 15s linear infinite",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        fadeIn: "fadeIn 0.2s ease-out",
        fadeOut: "fadeOut 0.2s ease-out",
        "collapse-down": "collapse-down 0.2s ease-out",
        "collapse-up": "collapse-up 0.2s ease-out",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
          input: "hsl(var(--sidebar-input))",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/forms")({ strategy: "class" })],
};
```

`nuxt.config.ts`

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },
  modules: [
    '@nuxtjs/tailwindcss',
    '@nuxtjs/color-mode',
    '@vueuse/nuxt',
    '@nuxt/icon',
    '@nuxt/fonts',
  ],
  tailwindcss: {
    exposeConfig: true,
    editorSupport: true,
  },
  colorMode: {
    classSuffix: '',
  },
  imports: {
    imports: [
      {
        from: 'tailwind-variants',
        name: 'tv',
      },
      {
        from: 'tailwind-variants',
        name: 'VariantProps',
        type: true,
      },
    ],
  },
});
```
